/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": `${process.env.REACT_APP_INTEGRATION}`,
  "tt": `${process.env.REACT_APP_TT}`,
  "version": "2020-11-20"
}

export default ebconfig;